const request = {
  processCode: 'PROC-1AC5A821-B938-4440-BBF9-0508B7FF18D9',
  conditionRule: [],
  formConfig: { 'sid-1234_5678': [] },
  nodeConfig: {},
  isCopyPublic: false,
  dirId: '16ac4de3216092d0456f40a488288896',
  oriDirId: '16ac4de3216092d0456f40a488288896',
  isPublishProcess: true,
  formVo: {
    uuid: 'FORM-DA4F9D7E-CD20-4FB4-A534-61C5AB40AA10',
    gmtCreated: 1558082035000,
    gmtModified: 1558082035000,
    attendanceType: null,
    iconUrl: 'common',
    pushSwitch: '0',
    memo: '',
    isDeleted: 'n',
    visibleRange: 'PRIVATE',
    formEngine: 'nfb',
    system: false,
    creator: '121102036226096223',
    name: '发发发',
    content: {
      icon: 'common',
      description: '',
      title: '发发发',
      commentRequired: '1',
      commentHiddenForProposer: '1',
      commentDescription: 'sadsdasd ',
      items: [
        { componentName: 'TextField', props: { placeholder: '请输入', label: '单行输入框', id: 'TextField-JVRR86SK' } },
        {
          componentName: 'TextareaField',
          props: { placeholder: '请输入', label: '多行输入框', id: 'TextareaField-JVRR86SI' },
        },
        {
          componentName: 'NumberField',
          props: { placeholder: '请输入数字', label: '数字输入框', id: 'NumberField-JVSVK5QZ' },
        },
        {
          componentName: 'DDSelectField',
          props: {
            placeholder: '请选择',
            options: ['选项1', '选项2', '选项3'],
            label: '单选框',
            id: 'DDSelectField-JVRR86SJ',
            required: true,
          },
        },
        {
          componentName: 'DDMultiSelectField',
          props: {
            placeholder: '请选择',
            options: [
              '选项1',
              '选项2',
              '选项3',
              '选项4',
              '选项5',
              '选项6',
              '选项7',
              '选项20',
              '选项19',
              '选项18',
              '选项17',
              '选项16',
              '选项15',
              '选项14',
              '选项13',
              '选项12',
              '选项11',
              '选项10',
              '选项9',
              '选项8',
            ],
            label: '多选框',
            id: 'DDMultiSelectField-JVSVK5QX',
          },
        },
        {
          componentName: 'DDDateField',
          props: { placeholder: '请选择', format: 'yyyy-MM-dd', label: '日期', unit: '天', id: 'DDDateField-JVSVK5R0' },
        },
        {
          componentName: 'DDDateRangeField',
          props: {
            placeholder: '请选择',
            format: 'yyyy-MM-dd',
            unit: '天',
            label: ['开始时间', '结束时间'],
            pushToCalendar: '0',
            id: 'DDDateRangeField-JVSVK5R1',
          },
        },
        { componentName: 'DDPhotoField', props: { label: '图片', id: 'DDPhotoField-JVSVK5QY' } },
      ],
      dirId: '16ac4de3216092d0456f40a488288896',
    },
    dirId: '16ac4de3216092d0456f40a488288896',
    condition: [],
  },
  processConfig: {
    name: '发起人',
    type: 'start',
    nodeId: 'sid-startevent',
    childNode: {
      name: '审批人',
      type: 'approver',
      prevId: 'sid-startevent',
      nodeId: 'sid-1234_5678',
      properties: {
        activateType: 'ONE_BY_ONE',
        agreeAll: false,
        allowTaskAppend: false,
        allowTaskRedirect: true,
        actionerRules: [
          {
            type: 'target_select',
            multi: 0,
            select: ['approvals'],
            range: {
              approvals: [
                { userName: '杨成浩', workNo: '064005684326245825' },
                { userName: '李剑飞', workNo: '116048066326107003' },
                { userName: '杨俊宁', workNo: '121102036226096223' },
              ],
            },
            isEmpty: false,
            key: 'manual_sid-1234_5678_30a8_b373',
          },
        ],
      },
      childNode: {
        name: '抄送人',
        type: 'notifier',
        prevId: 'sid-1234_5678',
        nodeId: '9955_7e43',
        properties: {
          actionerRules: [
            {
              select: ['allStaff'],
              range: { allStaff: null },
              multi: 1,
              type: 'target_select',
              key: 'manual_9955_7e43_0c96_39d8',
            },
          ],
        },
      },
    },
  },
  settings: [
    { type: 'appendEnable', value: 'n' },
    { type: 'duplicateRemoval', value: 'continuousFirst' },
    { type: 'static', value: '1' },
    { type: 'printType', value: '0' },
    { type: 'handSignConf', value: { handSignEnable: true, resignEnable: false } },
    { type: 'processConf', value: { submitEnable: true, submitterList: [] } },
    {
      type: 'properties',
      value: {
        static: '1',
        printType: '0',
        appendEnable: 'n',
        duplicateRemoval: 'continuousFirst',
        handSignConf: '{"handSignEnable":true,"resignEnable":false}',
      },
    },
    {
      type: 'microAppStatus',
      value: {
        hrmAppStatus: 0,
        alitripAppStatus: 0,
        attendanceAppStatus: 1,
        performanceAppStatus: 0,
        dingPayAppStatus: 0,
        dingDangAppStatus: 0,
        salaryAppStatus: false,
      },
    },
    { type: 'procAttendanceType', value: 0 },
    { type: 'bizCategoryId', value: '' },
  ],
}

const response = {
  processCode: 'PROC-1AC5A821-B938-4440-BBF9-0508B7FF18D9',
  formUuid: 'FORM-74E3B23C-9119-4277-823C-6E187E4C8DE5',
  processStatus: 'PUBLISHED',
  url: '',
}

export default {
  request,
  response,
}
